# Generated by Django 5.0.3 on 2024-04-01 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('pprice', models.FloatField(blank=True, default=None)),
                ('partners', models.ManyToManyField(to='main.partner')),
            ],
        ),
    ]
